#
# The contents of this file are subject to the terms of the Common Development and
# Distribution License (the License). You may not use this file except in compliance with the
# License.
#
# You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
# specific language governing permission and limitations under the License.
#
# When distributing Covered Software, include this CDDL Header Notice in each file and include
# the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
# Header, with the fields enclosed by brackets [] replaced by your own identifying
# information: "Portions copyright [year] [name of copyright owner]".
#
# Copyright 2015 ForgeRock AS.
#

########################################################################################################################
# Common handler section properties
########################################################################################################################
commonHandler=enabled
commonHandler=topics

########################################################################################################################
# Common handler plugin section properties
########################################################################################################################
commonHandlerPlugin=handlerFactory

########################################################################################################################
# JDBC handler section properties
########################################################################################################################
jdbcDatabaseConfig=databaseType
jdbcDatabaseConfig=jdbcUrl
jdbcDatabaseConfig=driverClassName
jdbcDatabaseConfig=username
jdbcDatabaseConfig=password
jdbcDatabaseConfig=connectionTimeout
jdbcDatabaseConfig=idleTimeout
jdbcDatabaseConfig=maxLifetime
jdbcDatabaseConfig=minIdle
jdbcDatabaseConfig=maxPoolSize
jdbcBuffering=bufferingEnabled
jdbcBuffering=bufferingMaxSize
jdbcBuffering=bufferingWriteInterval
jdbcBuffering=bufferingWriterThreads
jdbcBuffering=bufferingMaxBatchedEvents
